### ISSUE TITLE
Add jq to Pre-requisites in README

### ISSUE THREAD

**Issue by brakf** [aws-samples/service-catalog-engine-for-terraform-os#16]
Hello,

While deploying the project, I noticed that the jq command-line JSON processor is required but not mentioned in the pre-requisites section of the README. The absence of jq can lead to errors during deployment.

To help others avoid running into this issue, I suggest updating the README to include jq in the pre-requisites section.

Thank you!

**Comment by smaly-amazon** [comment]
Hello,

Thank you for pointing this out. We will update the Readme to include this.

**Comment by kshn01** [comment]
Hello,

We also need to install `python3.9-distutils`. I faced issue while running the script` ./bin/bash/deploy-tre.sh -r`.

Thank you.

**Comment by smaly-amazon** [comment]
@kshn01

Thanks for pointing that out. 

We just merged a change that uses a virtual environment for the automated installation and manual installation instructions. Python setuptools is included when creating a virtual environment.

We use setuptools which is a superset of distuitls. So I think the change to use a virtual environment will take care of this.
