### ISSUE TITLE
Error occurred during parameter parsing

### ISSUE THREAD

**Issue by kshn01** [aws-samples/service-catalog-engine-for-terraform-os#23]
`Error occurred during parameter parsing: RequestId: c1a15c5b-1e4e-46db-a5d1-cd924b33219c Error: Runtime exited with error: exit status 1`

I am following [Getting started with Terraform open source](https://docs.aws.amazon.com/servicecatalog/latest/adminguide/getstarted-Terraform.html). The error occurs while launching product from end user.

**Comment by smaly-amazon** [comment]
Hi @kshn01,

I apologize that you are having this issue.

This problem looks similar to the one reported here:
https://github.com/aws-samples/service-catalog-engine-for-terraform-os/issues/15

We are working on updating the installation process to address this. To work around this now, please do the following:

1. Delete the SAM-TRE stack.

2. Run these commands from the root directory of the repo.

```
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 sam build

sam deploy --s3-bucket terraform-engine-bootstrap-<account>-<region> --stack-name SAM-TRE --capabilities CAPABILITY_NAMED_IAM
```

Please let us know if you are still having this issue after following those steps.

**Comment by kshn01** [comment]
Hi @smaly-amazon 

It worked for me. Thanks for the help.

Thank you!
