### ISSUE TITLE
AmazonEC2RoleforSSM will be deprecated soon.

### ISSUE THREAD

**Issue by gutozntt** [aws-samples/service-catalog-engine-for-terraform-os#25]
File template.yaml - line 662

- !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonEC2RoleforSSM

Since this policy will be deprecated soon, I recommend you guys using AmazonSSMManagedInstanceCore. 

Make sure to remove the /service-role/.

- !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore

**Comment by zipengw27** [comment]
Thank you @gutozntt . We have merged a PR that uses the recommend policies instead.
