### ISSUE TITLE
How to remove the stack?

### ISSUE THREAD

**Issue by aws-hebrew-book** [aws-samples/service-catalog-engine-for-terraform-os#26]
Hello,
I've installed the code on our integration AWS environment for testing purposes, now I want to remove it, how can I do it?

**Comment by smaly-amazon** [comment]
Hi,

Thanks for the question.

The Terraform Reference Engine consists of two CloudFormation stacks. To remove the engine from your account, you need to delete these stacks.

1. You need to delete the stack named SAM-TRE.

Note that the stack contains a couple buckets. As with any S3 buckets, they need to be emtied before they can be deleted. 

The names of the buckets are:
* `sc-terraform-engine-state-<account ID>-<region>`
    * This bucket has a fairly resrictive permissions policy on it, since it is used to store Teraform state files. You may need to modify or delete the bucket policy before you can empty the bucket.
* `sc-terraform-engine-logging-<account ID>-<region>`

2. Once the SAM-TRE stack has been deleted, then you can delete the stack named Bootstrap-TRE.

**Comment by aws-hebrew-book** [comment]
Got it. Worth adding it to the README
