### ISSUE TITLE
Please provide estimated cost for operation

### ISSUE THREAD

**Issue by aws-hebrew-book** [aws-samples/service-catalog-engine-for-terraform-os#30]
How much does it cost to run this engine? I need a ballpark estimation

**Comment by smaly-amazon** [comment]
Hi,

Thanks for the question.

One component of the cost for using Terraform Open-Source products is Service Catalog pricing.
* https://aws.amazon.com/servicecatalog/pricing/

Another component depends on the volume. You can estimate the cost from the engine's resources based on your forecasted volume using the AWS pricing calculator or other cost-estimation tools.

**Comment by aws-hebrew-book** [comment]
Thank you for the prompt response. I talked with Danilo about it. I'm looking more into the hidden operational cost, I saw that you are running EC2, you have NATs and so on, how much these components costs?

Let's say deploying a template takes 10 min, and I'm doing that 5 times a week? Putting aside the service catalog cost, how much am I expected to pay for running this engine?

**Comment by aws-hebrew-book** [comment]
You ate right, I meant fixed costs. Thank you. I think it's worth adding costs details to the README as well
