### ISSUE TITLE
Mantain variable values during service catalog product version update

### ISSUE THREAD

**Issue by campaand** [aws-samples/service-catalog-engine-for-terraform-os#37]
Hello,
I noticed that when upgrading one Service Catalog product from one version to another, variables values (for non-default variables) are blank instead of prepopulated with previous version values.

For example: I created first version of my product (v1.0) with a non-default `bucket_name` variable, i launched the product with that variable setted to `my-s3-bucket-ughxrew`. 
After, I created another version of my product (v1.1) with some new changes.
When I updated the already provisioned product with my new version, the variable field `bucket_name` showed in the update prompt is  blank, instead of setted to `my-s3-bucket-ughxrew`.

I'm thinking about the same situation in case I have more than 50 or 100 variables and I have to put them all back by hand.

Would it be possible to find a way to extract the values ​​of the variables from the terraform state saved on S3 and show them already populated during the update?

Thank you in advance for your time and support

**Comment by smaly-amazon** [comment]
Hi @campaand,

Thanks for mentioning this.

The behavior you describe is part of the AWS Service Catalog console and not specific to this engine. Please report this to AWS support so the Service Catalog team can investigate.

Thanks.
