### ISSUE TITLE
Deploy Engine in Existing Infrastructure

### ISSUE THREAD

**Issue by davsalazar** [aws-samples/service-catalog-engine-for-terraform-os#41]
It'd be helpful to be able to deploy the engine with existing infra. More specifically, it'd be great to have the option to deploy just the essential engine components, like the queue and ASG. I think that'd be a great help for adopting this. I see contributions are not being accepted at this time, so I'm creating this issue. Thank you!

**Comment by smaly-amazon** [comment]
Hi,

Thanks for this feedback. This is discussed in a similar issue: #38.

Because Service Catalog customers have a wide variety of security needs and account setups, we built the engine to meet the most frequent cases, allowing that some customers may want to fork/customize the code.
