### ISSUE TITLE
Parameter parsing in the form of multiple select/select

### ISSUE THREAD

**Issue by itjobs-levi** [aws-samples/service-catalog-engine-for-terraform-os#52]
When provisioning the aws service catalog with terraform product, is there any way to create an input box in the form of select/multiple select in the parameters?
Currently, it is an input form in the form of a string, so it is inconvenient to enter a list or map.

**Comment by smaly-amazon** [comment]
Thanks for this request. We will consider it for a future change to Service Catalog.

**Comment by itjobs-levi** [comment]
thank you
