### ISSUE TITLE
There was an error loading parameters for product version 

### ISSUE THREAD

**Issue by goural** [aws-samples/service-catalog-engine-for-terraform-os#53]
<img width="700" alt="image" src="https://github.com/aws-samples/service-catalog-engine-for-terraform-os/assets/29977985/2d68c76c-4709-41ad-89b3-667fbadec544">

I am getting this error in service catalog> Product list > product_id >product_version when I click on Provisioning parameters .

The error message shows - Error
Error occurred during parameter parsing: LaunchRoleArn is required and must be non empty

I have tried passing both LaunchRoleArn and LaunchRolename.

Any suggestion is much appreciated as I do not find any other document related to this.

**Comment by smaly-amazon** [comment]
Hello,

The error indicates that the product you are trying to provision does not have a launch role associated with it. You need to add a launch role constraint to the product/portfolio in the Service Catalog console or using the CreateConstraint API.

https://docs.aws.amazon.com/servicecatalog/latest/adminguide/getstarted-launchrole-Terraform.html

* I have tried passing both LaunchRoleArn and LaunchRolename.

I'm not sure what you mean by this. Launch role is not an input to any Service Catalog API.

**Comment by goural** [comment]
The issue is resolved by updating terraform version to latest (**1.5.0**) TerraformCliVersion. This solved the issue with provisioning parameters in the service catalog product version. Currently in repo default is 1.2.8 
ref - https://github.com/aws-samples/service-catalog-engine-for-terraform-os/blob/19d307db8d38201e42e890a50d85df9053f6ed54/template.yaml#L46
