### ISSUE TITLE
Updating source code and terraform version in running terraform open source engine setup

### ISSUE THREAD

**Issue by goural** [aws-samples/service-catalog-engine-for-terraform-os#54]
Please help the steps to update the already running terraform open source engine setup with latest code. Also if we just want to update the TerraformCliVersion, how we can do it ?

I have installed Terraform OSE using the script to automatically install setup (./bin/bash/deploy-tre.sh -r) which is running fine. How the existing setup can be updated without deleting the entire setup.

**Comment by smaly-amazon** [comment]
Hi @goural,

To update an existing installation of the engine, you can follow the instructions in the Readme. 

If you run deploy-tre.sh -r again, it will update your existing engine. It will also pause processing so EC2 instances can be safely restarted.

Or, you can follow the manual installation steps to update an existing engine.

either way, you will update your current engine environment and don't need to delete and recreate everything.

---

To set the engine to a particular Terraform version, follow the manual installation steps. When you get to the step to run sam deploy, use the --parameter-overrides option to set the Terraform version and any other parameters from the template.yaml file that suit your needs.

**Comment by goural** [comment]
I have tried updating the template.yaml with the new TerraformCliVersion and reran the deploy-tre.sh -r again. It did recreated a new ec2 but the terraform engine was not updated on that instance.
