### ISSUE TITLE
Dynamic parameters retrieved from AWS API

### ISSUE THREAD

**Issue by vmwiz** [aws-samples/service-catalog-engine-for-terraform-os#78]
I was a bit disappointed by the Parameter Parser being quite limited in terms of UX, I didn't felt comfortable asking my users to fill values like a `vpc_id` or a `route53_zone_id` until... Until I tried to set my terraform variable type to one of the [AWS-specific parameter types](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html#aws-specific-parameter-types) and suddenly my product launch form became more dynamic ! 😀 

Thanks to the way you generate the variables overrides it is possible to inject some CloudFormation parameters properties, it's maybe something to investigate to support more of them for validation purposes (AllowedPattern, AllowedValues, MinLenght, ...) and why not SSM Parameters to populate dropdowns?

How to reproduce?

```
variable "vpc_id" {
  description = "VPC where to create subnets"
  type        = "AWS::EC2::VPC::Id"
}
```

Result:

![image](https://github.com/aws-samples/service-catalog-engine-for-terraform-os/assets/17565465/3e128309-d0e5-479c-948d-ce5b8c9d57ff)

**Comment by jack-parsons-bjss** [comment]
@vmwiz How come this issue is closed? I'd really like to be able to specify similar restrictions for some of my product fields! Did you find a way to achieve this? The AWS specific types are somewhat limited.
