### ISSUE TITLE
Update AMI version for EC2 runner

### ISSUE THREAD

**Issue by cndsv** [aws-samples/service-catalog-engine-for-terraform-os#94]
Hello
the current default public AMI for runners seems to be an AL2 type AMI:

_template.yaml_
```
 ServerLatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
```

_amzn2-ami-hvm-x86_64-gp2_ links to _ami-0a09a25a3d0574b76 (Amazon Linux 2 AMI 2.0.20241113.1 x86_64 HVM gp2)_

For AL2 the latest built-in python version seems to be Python 3.8.

Is it possible to get the newer AMI type AL2023 for runners which would allow to use newer packages and upgrade Python  (linked to issue #93) ?

Thank you

**Comment by aws-dlaqua** [comment]
Hey cndsv,

That is a public SSM parameter that should be kept up to date with latest AMIs, but we (AWS Service Catalog) do not own or manage that. With that said, note that this is only the default value used when an AMI is not manually specified as an input to the stack creation/update. You can override it with the latest AMI if you that parameter doesn't have the one you need.

Drew

**Comment by cndsv** [comment]
Thanks for your answer. We'll try the override

**Comment by cndsv** [comment]
FYI : overriding with /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64 leads to multiple issues

- During stack deployment:

```
TerraformAutoscalingGroup
Failure reason
Received 0 SUCCESS signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement
```

- Debugging shows also that the autoscaling launch template is not compatible with the new AMI

```
024-12-18 16:01:04,398 [INFO] Running config install_terraform
2024-12-18 16:01:05,577 [ERROR] yum-utils is not available to be installed
2024-12-18 16:01:05,577 [ERROR] Error encountered during build of install_terraform: Yum does not have yum-utils available for installation
```
the whole userdata part does not work correctly.
pip is also not available.

Currently working on updating the template to use dnf and installing recent python version and pip.
